remote_theme: noicelink/jekyll.noice.link

title: noice.link Documentation
description: A noice URL shortener
author: noice.link

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
